[General]
;DXScanCodes: https://ck.uesp.net/wiki/Input_Script
iOpenMenuKeycode=49
iShowDetailsKeycode=33
iShowDetailsGamepadKeycode=273
iActionButtonKeycode=34
iActionButtonGamepadKeycode=279
iNavLeft=16
iNavRight=19
iNavLeftGamepad=274
iNavRightGamepad=275

;Change it to 0 to disable blur effect in the menu
iEnableBlur = 1

; Enable debug logging
bDebugMode=true